#ifndef GAME_ASSISTANT_GLOBAL_H_
#define GAME_ASSISTANT_GLOBAL_H_

#define NAMESPACE_GAME_ASSISTANT_BEGIN namespace game_assitant {
#define NAMESPACE_GAME_ASSISTANT_END }
#define USING_NAMESPACE_GAME_ASSISTANT using namespace game_assitant;
#endif // GAME_ASSISTANT_GLOBAL_H
